//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace MMCoreConnector.WRAccount {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AccountEndpointBinding", Namespace="http://session.kernel.cmp.com/")]
    public partial class AccountService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback createAccountWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback findAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback findAccountByCriteriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback findAccountByLdapSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback findByLoginOnDocsWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCriteriaNamesListOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeAccountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AccountService() {
            this.Url = global::MMCoreConnector.Properties.Settings.Default.MMCoreConnector_WRAccount_AccountService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event createAccountWSCompletedEventHandler createAccountWSCompleted;
        
        /// <remarks/>
        public event findAccountCompletedEventHandler findAccountCompleted;
        
        /// <remarks/>
        public event findAccountByCriteriaCompletedEventHandler findAccountByCriteriaCompleted;
        
        /// <remarks/>
        public event findAccountByLdapSearchCompletedEventHandler findAccountByLdapSearchCompleted;
        
        /// <remarks/>
        public event findByLoginOnDocsWSCompletedEventHandler findByLoginOnDocsWSCompleted;
        
        /// <remarks/>
        public event getCriteriaNamesListCompletedEventHandler getCriteriaNamesListCompleted;
        
        /// <remarks/>
        public event removeAccountCompletedEventHandler removeAccountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://session.kernel.cmp.com/", ResponseNamespace="http://session.kernel.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusPerson createAccountWS(person person) {
            object[] results = this.Invoke("createAccountWS", new object[] {
                        person});
            return ((mproxyOperationStatusPerson)(results[0]));
        }
        
        /// <remarks/>
        public void createAccountWSAsync(person person) {
            this.createAccountWSAsync(person, null);
        }
        
        /// <remarks/>
        public void createAccountWSAsync(person person, object userState) {
            if ((this.createAccountWSOperationCompleted == null)) {
                this.createAccountWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateAccountWSOperationCompleted);
            }
            this.InvokeAsync("createAccountWS", new object[] {
                        person}, this.createAccountWSOperationCompleted, userState);
        }
        
        private void OncreateAccountWSOperationCompleted(object arg) {
            if ((this.createAccountWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createAccountWSCompleted(this, new createAccountWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://session.kernel.cmp.com/", ResponseNamespace="http://session.kernel.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusPerson findAccount(string userId) {
            object[] results = this.Invoke("findAccount", new object[] {
                        userId});
            return ((mproxyOperationStatusPerson)(results[0]));
        }
        
        /// <remarks/>
        public void findAccountAsync(string userId) {
            this.findAccountAsync(userId, null);
        }
        
        /// <remarks/>
        public void findAccountAsync(string userId, object userState) {
            if ((this.findAccountOperationCompleted == null)) {
                this.findAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAccountOperationCompleted);
            }
            this.InvokeAsync("findAccount", new object[] {
                        userId}, this.findAccountOperationCompleted, userState);
        }
        
        private void OnfindAccountOperationCompleted(object arg) {
            if ((this.findAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findAccountCompleted(this, new findAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://session.kernel.cmp.com/", ResponseNamespace="http://session.kernel.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusPerson findAccountByCriteria(string criteriaId, string pattern, long maximumRecords) {
            object[] results = this.Invoke("findAccountByCriteria", new object[] {
                        criteriaId,
                        pattern,
                        maximumRecords});
            return ((mproxyOperationStatusPerson)(results[0]));
        }
        
        /// <remarks/>
        public void findAccountByCriteriaAsync(string criteriaId, string pattern, long maximumRecords) {
            this.findAccountByCriteriaAsync(criteriaId, pattern, maximumRecords, null);
        }
        
        /// <remarks/>
        public void findAccountByCriteriaAsync(string criteriaId, string pattern, long maximumRecords, object userState) {
            if ((this.findAccountByCriteriaOperationCompleted == null)) {
                this.findAccountByCriteriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAccountByCriteriaOperationCompleted);
            }
            this.InvokeAsync("findAccountByCriteria", new object[] {
                        criteriaId,
                        pattern,
                        maximumRecords}, this.findAccountByCriteriaOperationCompleted, userState);
        }
        
        private void OnfindAccountByCriteriaOperationCompleted(object arg) {
            if ((this.findAccountByCriteriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findAccountByCriteriaCompleted(this, new findAccountByCriteriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://session.kernel.cmp.com/", ResponseNamespace="http://session.kernel.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusPerson findAccountByLdapSearch(string ldapSearchClause, long maximumRecords) {
            object[] results = this.Invoke("findAccountByLdapSearch", new object[] {
                        ldapSearchClause,
                        maximumRecords});
            return ((mproxyOperationStatusPerson)(results[0]));
        }
        
        /// <remarks/>
        public void findAccountByLdapSearchAsync(string ldapSearchClause, long maximumRecords) {
            this.findAccountByLdapSearchAsync(ldapSearchClause, maximumRecords, null);
        }
        
        /// <remarks/>
        public void findAccountByLdapSearchAsync(string ldapSearchClause, long maximumRecords, object userState) {
            if ((this.findAccountByLdapSearchOperationCompleted == null)) {
                this.findAccountByLdapSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAccountByLdapSearchOperationCompleted);
            }
            this.InvokeAsync("findAccountByLdapSearch", new object[] {
                        ldapSearchClause,
                        maximumRecords}, this.findAccountByLdapSearchOperationCompleted, userState);
        }
        
        private void OnfindAccountByLdapSearchOperationCompleted(object arg) {
            if ((this.findAccountByLdapSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findAccountByLdapSearchCompleted(this, new findAccountByLdapSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://session.kernel.cmp.com/", ResponseNamespace="http://session.kernel.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusPerson findByLoginOnDocsWS(string server, string login) {
            object[] results = this.Invoke("findByLoginOnDocsWS", new object[] {
                        server,
                        login});
            return ((mproxyOperationStatusPerson)(results[0]));
        }
        
        /// <remarks/>
        public void findByLoginOnDocsWSAsync(string server, string login) {
            this.findByLoginOnDocsWSAsync(server, login, null);
        }
        
        /// <remarks/>
        public void findByLoginOnDocsWSAsync(string server, string login, object userState) {
            if ((this.findByLoginOnDocsWSOperationCompleted == null)) {
                this.findByLoginOnDocsWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindByLoginOnDocsWSOperationCompleted);
            }
            this.InvokeAsync("findByLoginOnDocsWS", new object[] {
                        server,
                        login}, this.findByLoginOnDocsWSOperationCompleted, userState);
        }
        
        private void OnfindByLoginOnDocsWSOperationCompleted(object arg) {
            if ((this.findByLoginOnDocsWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findByLoginOnDocsWSCompleted(this, new findByLoginOnDocsWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://session.kernel.cmp.com/", ResponseNamespace="http://session.kernel.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<searchingCriteria>[] getCriteriaNamesList() {
            object[] results = this.Invoke("getCriteriaNamesList", new object[0]);
            return ((System.Nullable<searchingCriteria>[])(results[0]));
        }
        
        /// <remarks/>
        public void getCriteriaNamesListAsync() {
            this.getCriteriaNamesListAsync(null);
        }
        
        /// <remarks/>
        public void getCriteriaNamesListAsync(object userState) {
            if ((this.getCriteriaNamesListOperationCompleted == null)) {
                this.getCriteriaNamesListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCriteriaNamesListOperationCompleted);
            }
            this.InvokeAsync("getCriteriaNamesList", new object[0], this.getCriteriaNamesListOperationCompleted, userState);
        }
        
        private void OngetCriteriaNamesListOperationCompleted(object arg) {
            if ((this.getCriteriaNamesListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCriteriaNamesListCompleted(this, new getCriteriaNamesListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://session.kernel.cmp.com/", ResponseNamespace="http://session.kernel.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public void removeAccount(string arg0) {
            this.Invoke("removeAccount", new object[] {
                        arg0});
        }
        
        /// <remarks/>
        public void removeAccountAsync(string arg0) {
            this.removeAccountAsync(arg0, null);
        }
        
        /// <remarks/>
        public void removeAccountAsync(string arg0, object userState) {
            if ((this.removeAccountOperationCompleted == null)) {
                this.removeAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveAccountOperationCompleted);
            }
            this.InvokeAsync("removeAccount", new object[] {
                        arg0}, this.removeAccountOperationCompleted, userState);
        }
        
        private void OnremoveAccountOperationCompleted(object arg) {
            if ((this.removeAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeAccountCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.kernel.cmp.com/")]
    public partial class person {
        
        private string ackField;
        
        private string authCertificateField;
        
        private string autocertificationActiveField;
        
        private bool boolAckField;
        
        private string caDomainField;
        
        private bool certifiedField;
        
        private string cityField;
        
        private string commercialActionField;
        
        private string countryField;
        
        private string descriptionField;
        
        private string dmiField;
        
        private string emailForwardField;
        
        private string enabledField;
        
        private string encCertificateField;
        
        private string encodingTypeField;
        
        private string etkField;
        
        private string faxField;
        
        private string firstNameField;
        
        private string genderField;
        
        private string inamiField;
        
        private string institutionField;
        
        private string langueField;
        
        private string lastNameField;
        
        private string lastconnectiondateField;
        
        private string localeStrField;
        
        private string loginField;
        
        private string mailField;
        
        private string mexiAddressField;
        
        private string mexiBackupField;
        
        private string mobilephoneField;
        
        private string nissField;
        
        private string oldIPField;
        
        private string oldSystemIdField;
        
        private string packageNameField;
        
        private string passwordField;
        
        private string pincodeField;
        
        private string pkeyField;
        
        private string pkeyehealthField;
        
        private string postalAddressField;
        
        private string postalCodeField;
        
        private bool principalField;
        
        private string principalUserNameField;
        
        private string provinceField;
        
        private string registrationDateField;
        
        private string roleField;
        
        private bool senderField;
        
        private bool senderInvisibleField;
        
        private string subscriptiondocsField;
        
        private string telephoneField;
        
        private string upgradedField;
        
        private string userCertificateField;
        
        private string userpublicField;
        
        private string usetranscodorField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ack {
            get {
                return this.ackField;
            }
            set {
                this.ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authCertificate {
            get {
                return this.authCertificateField;
            }
            set {
                this.authCertificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autocertificationActive {
            get {
                return this.autocertificationActiveField;
            }
            set {
                this.autocertificationActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool boolAck {
            get {
                return this.boolAckField;
            }
            set {
                this.boolAckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string caDomain {
            get {
                return this.caDomainField;
            }
            set {
                this.caDomainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool certified {
            get {
                return this.certifiedField;
            }
            set {
                this.certifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commercialAction {
            get {
                return this.commercialActionField;
            }
            set {
                this.commercialActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dmi {
            get {
                return this.dmiField;
            }
            set {
                this.dmiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string emailForward {
            get {
                return this.emailForwardField;
            }
            set {
                this.emailForwardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encCertificate {
            get {
                return this.encCertificateField;
            }
            set {
                this.encCertificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encodingType {
            get {
                return this.encodingTypeField;
            }
            set {
                this.encodingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string etk {
            get {
                return this.etkField;
            }
            set {
                this.etkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inami {
            get {
                return this.inamiField;
            }
            set {
                this.inamiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string institution {
            get {
                return this.institutionField;
            }
            set {
                this.institutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string langue {
            get {
                return this.langueField;
            }
            set {
                this.langueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastconnectiondate {
            get {
                return this.lastconnectiondateField;
            }
            set {
                this.lastconnectiondateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string localeStr {
            get {
                return this.localeStrField;
            }
            set {
                this.localeStrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mexiAddress {
            get {
                return this.mexiAddressField;
            }
            set {
                this.mexiAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mexiBackup {
            get {
                return this.mexiBackupField;
            }
            set {
                this.mexiBackupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mobilephone {
            get {
                return this.mobilephoneField;
            }
            set {
                this.mobilephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string niss {
            get {
                return this.nissField;
            }
            set {
                this.nissField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oldIP {
            get {
                return this.oldIPField;
            }
            set {
                this.oldIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oldSystemId {
            get {
                return this.oldSystemIdField;
            }
            set {
                this.oldSystemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string packageName {
            get {
                return this.packageNameField;
            }
            set {
                this.packageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pincode {
            get {
                return this.pincodeField;
            }
            set {
                this.pincodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pkey {
            get {
                return this.pkeyField;
            }
            set {
                this.pkeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pkeyehealth {
            get {
                return this.pkeyehealthField;
            }
            set {
                this.pkeyehealthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string postalAddress {
            get {
                return this.postalAddressField;
            }
            set {
                this.postalAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string principalUserName {
            get {
                return this.principalUserNameField;
            }
            set {
                this.principalUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string registrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool senderInvisible {
            get {
                return this.senderInvisibleField;
            }
            set {
                this.senderInvisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subscriptiondocs {
            get {
                return this.subscriptiondocsField;
            }
            set {
                this.subscriptiondocsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string upgraded {
            get {
                return this.upgradedField;
            }
            set {
                this.upgradedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userCertificate {
            get {
                return this.userCertificateField;
            }
            set {
                this.userCertificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userpublic {
            get {
                return this.userpublicField;
            }
            set {
                this.userpublicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usetranscodor {
            get {
                return this.usetranscodorField;
            }
            set {
                this.usetranscodorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.kernel.cmp.com/")]
    public partial class mproxyOperationStatusPerson {
        
        private string detailedInfoField;
        
        private mproxyOperationResult operationResultField;
        
        private bool operationResultFieldSpecified;
        
        private person[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string detailedInfo {
            get {
                return this.detailedInfoField;
            }
            set {
                this.detailedInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mproxyOperationResult operationResult {
            get {
                return this.operationResultField;
            }
            set {
                this.operationResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationResultSpecified {
            get {
                return this.operationResultFieldSpecified;
            }
            set {
                this.operationResultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public person[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.kernel.cmp.com/")]
    public enum mproxyOperationResult {
        
        /// <remarks/>
        MPROXY_RESULT_OK,
        
        /// <remarks/>
        MPROXY_RESULT_FAILED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://session.kernel.cmp.com/")]
    public enum searchingCriteria {
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        CRITERIA_INAMI,
        
        /// <remarks/>
        CRITERIA_MEXI_ADDRESS,
        
        /// <remarks/>
        CRITERIA_UID,
        
        /// <remarks/>
        CRITERIA_NISS,
        
        /// <remarks/>
        CRITERIA_LAST_NAME,
        
        /// <remarks/>
        CRITERIA_FIRST_NAME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void createAccountWSCompletedEventHandler(object sender, createAccountWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createAccountWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createAccountWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusPerson Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusPerson)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void findAccountCompletedEventHandler(object sender, findAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusPerson Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusPerson)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void findAccountByCriteriaCompletedEventHandler(object sender, findAccountByCriteriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findAccountByCriteriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findAccountByCriteriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusPerson Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusPerson)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void findAccountByLdapSearchCompletedEventHandler(object sender, findAccountByLdapSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findAccountByLdapSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findAccountByLdapSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusPerson Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusPerson)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void findByLoginOnDocsWSCompletedEventHandler(object sender, findByLoginOnDocsWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findByLoginOnDocsWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findByLoginOnDocsWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusPerson Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusPerson)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getCriteriaNamesListCompletedEventHandler(object sender, getCriteriaNamesListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCriteriaNamesListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCriteriaNamesListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Nullable<searchingCriteria>[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<searchingCriteria>[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void removeAccountCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591