//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace MMCoreConnector.WRDiagnostics {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DiagnosticsServiceSoapBinding", Namespace="http://operations.mule.mproxy.cmp.com/")]
    public partial class DiagnosticsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getErrorByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMbeanAttributeOperationCompleted;
        
        private System.Threading.SendOrPostCallback exportErrorsToFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback clearErrorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkPortsListenOperationCompleted;
        
        private System.Threading.SendOrPostCallback findLastErrorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback findAllErrorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeErrorByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkPortsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DiagnosticsService() {
            this.Url = global::MMCoreConnector.Properties.Settings.Default.MMCoreConnector_WRDdiagnostics_DiagnosticsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getErrorByIdCompletedEventHandler getErrorByIdCompleted;
        
        /// <remarks/>
        public event getMbeanAttributeCompletedEventHandler getMbeanAttributeCompleted;
        
        /// <remarks/>
        public event exportErrorsToFileCompletedEventHandler exportErrorsToFileCompleted;
        
        /// <remarks/>
        public event clearErrorsCompletedEventHandler clearErrorsCompleted;
        
        /// <remarks/>
        public event checkPortsListenCompletedEventHandler checkPortsListenCompleted;
        
        /// <remarks/>
        public event findLastErrorsCompletedEventHandler findLastErrorsCompleted;
        
        /// <remarks/>
        public event findAllErrorsCompletedEventHandler findAllErrorsCompleted;
        
        /// <remarks/>
        public event removeErrorByIdCompletedEventHandler removeErrorByIdCompleted;
        
        /// <remarks/>
        public event checkPortsCompletedEventHandler checkPortsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.mule.mproxy.cmp.com/", ResponseNamespace="http://operations.mule.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusError getErrorById(int arg0) {
            object[] results = this.Invoke("getErrorById", new object[] {
                        arg0});
            return ((mproxyOperationStatusError)(results[0]));
        }
        
        /// <remarks/>
        public void getErrorByIdAsync(int arg0) {
            this.getErrorByIdAsync(arg0, null);
        }
        
        /// <remarks/>
        public void getErrorByIdAsync(int arg0, object userState) {
            if ((this.getErrorByIdOperationCompleted == null)) {
                this.getErrorByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetErrorByIdOperationCompleted);
            }
            this.InvokeAsync("getErrorById", new object[] {
                        arg0}, this.getErrorByIdOperationCompleted, userState);
        }
        
        private void OngetErrorByIdOperationCompleted(object arg) {
            if ((this.getErrorByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getErrorByIdCompleted(this, new getErrorByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.mule.mproxy.cmp.com/", ResponseNamespace="http://operations.mule.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus getMbeanAttribute(string sever, string service, string attribute) {
            object[] results = this.Invoke("getMbeanAttribute", new object[] {
                        sever,
                        service,
                        attribute});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void getMbeanAttributeAsync(string sever, string service, string attribute) {
            this.getMbeanAttributeAsync(sever, service, attribute, null);
        }
        
        /// <remarks/>
        public void getMbeanAttributeAsync(string sever, string service, string attribute, object userState) {
            if ((this.getMbeanAttributeOperationCompleted == null)) {
                this.getMbeanAttributeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMbeanAttributeOperationCompleted);
            }
            this.InvokeAsync("getMbeanAttribute", new object[] {
                        sever,
                        service,
                        attribute}, this.getMbeanAttributeOperationCompleted, userState);
        }
        
        private void OngetMbeanAttributeOperationCompleted(object arg) {
            if ((this.getMbeanAttributeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMbeanAttributeCompleted(this, new getMbeanAttributeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.mule.mproxy.cmp.com/", ResponseNamespace="http://operations.mule.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus exportErrorsToFile() {
            object[] results = this.Invoke("exportErrorsToFile", new object[0]);
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void exportErrorsToFileAsync() {
            this.exportErrorsToFileAsync(null);
        }
        
        /// <remarks/>
        public void exportErrorsToFileAsync(object userState) {
            if ((this.exportErrorsToFileOperationCompleted == null)) {
                this.exportErrorsToFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportErrorsToFileOperationCompleted);
            }
            this.InvokeAsync("exportErrorsToFile", new object[0], this.exportErrorsToFileOperationCompleted, userState);
        }
        
        private void OnexportErrorsToFileOperationCompleted(object arg) {
            if ((this.exportErrorsToFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.exportErrorsToFileCompleted(this, new exportErrorsToFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.mule.mproxy.cmp.com/", ResponseNamespace="http://operations.mule.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus clearErrors() {
            object[] results = this.Invoke("clearErrors", new object[0]);
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void clearErrorsAsync() {
            this.clearErrorsAsync(null);
        }
        
        /// <remarks/>
        public void clearErrorsAsync(object userState) {
            if ((this.clearErrorsOperationCompleted == null)) {
                this.clearErrorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnclearErrorsOperationCompleted);
            }
            this.InvokeAsync("clearErrors", new object[0], this.clearErrorsOperationCompleted, userState);
        }
        
        private void OnclearErrorsOperationCompleted(object arg) {
            if ((this.clearErrorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.clearErrorsCompleted(this, new clearErrorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.mule.mproxy.cmp.com/", ResponseNamespace="http://operations.mule.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus checkPortsListen(string host, string portsToCheckDelimitedBySemicolumn, int timeOutInMillis) {
            object[] results = this.Invoke("checkPortsListen", new object[] {
                        host,
                        portsToCheckDelimitedBySemicolumn,
                        timeOutInMillis});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void checkPortsListenAsync(string host, string portsToCheckDelimitedBySemicolumn, int timeOutInMillis) {
            this.checkPortsListenAsync(host, portsToCheckDelimitedBySemicolumn, timeOutInMillis, null);
        }
        
        /// <remarks/>
        public void checkPortsListenAsync(string host, string portsToCheckDelimitedBySemicolumn, int timeOutInMillis, object userState) {
            if ((this.checkPortsListenOperationCompleted == null)) {
                this.checkPortsListenOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckPortsListenOperationCompleted);
            }
            this.InvokeAsync("checkPortsListen", new object[] {
                        host,
                        portsToCheckDelimitedBySemicolumn,
                        timeOutInMillis}, this.checkPortsListenOperationCompleted, userState);
        }
        
        private void OncheckPortsListenOperationCompleted(object arg) {
            if ((this.checkPortsListenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkPortsListenCompleted(this, new checkPortsListenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.mule.mproxy.cmp.com/", ResponseNamespace="http://operations.mule.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusError findLastErrors(int maximumErrors) {
            object[] results = this.Invoke("findLastErrors", new object[] {
                        maximumErrors});
            return ((mproxyOperationStatusError)(results[0]));
        }
        
        /// <remarks/>
        public void findLastErrorsAsync(int maximumErrors) {
            this.findLastErrorsAsync(maximumErrors, null);
        }
        
        /// <remarks/>
        public void findLastErrorsAsync(int maximumErrors, object userState) {
            if ((this.findLastErrorsOperationCompleted == null)) {
                this.findLastErrorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindLastErrorsOperationCompleted);
            }
            this.InvokeAsync("findLastErrors", new object[] {
                        maximumErrors}, this.findLastErrorsOperationCompleted, userState);
        }
        
        private void OnfindLastErrorsOperationCompleted(object arg) {
            if ((this.findLastErrorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findLastErrorsCompleted(this, new findLastErrorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.mule.mproxy.cmp.com/", ResponseNamespace="http://operations.mule.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusError findAllErrors() {
            object[] results = this.Invoke("findAllErrors", new object[0]);
            return ((mproxyOperationStatusError)(results[0]));
        }
        
        /// <remarks/>
        public void findAllErrorsAsync() {
            this.findAllErrorsAsync(null);
        }
        
        /// <remarks/>
        public void findAllErrorsAsync(object userState) {
            if ((this.findAllErrorsOperationCompleted == null)) {
                this.findAllErrorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAllErrorsOperationCompleted);
            }
            this.InvokeAsync("findAllErrors", new object[0], this.findAllErrorsOperationCompleted, userState);
        }
        
        private void OnfindAllErrorsOperationCompleted(object arg) {
            if ((this.findAllErrorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findAllErrorsCompleted(this, new findAllErrorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.mule.mproxy.cmp.com/", ResponseNamespace="http://operations.mule.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus removeErrorById(int errorId) {
            object[] results = this.Invoke("removeErrorById", new object[] {
                        errorId});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void removeErrorByIdAsync(int errorId) {
            this.removeErrorByIdAsync(errorId, null);
        }
        
        /// <remarks/>
        public void removeErrorByIdAsync(int errorId, object userState) {
            if ((this.removeErrorByIdOperationCompleted == null)) {
                this.removeErrorByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveErrorByIdOperationCompleted);
            }
            this.InvokeAsync("removeErrorById", new object[] {
                        errorId}, this.removeErrorByIdOperationCompleted, userState);
        }
        
        private void OnremoveErrorByIdOperationCompleted(object arg) {
            if ((this.removeErrorByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeErrorByIdCompleted(this, new removeErrorByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.mule.mproxy.cmp.com/", ResponseNamespace="http://operations.mule.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus checkPorts(string host, string portsToCheckDelimitedBySemicolumn, int timeOutInMillis) {
            object[] results = this.Invoke("checkPorts", new object[] {
                        host,
                        portsToCheckDelimitedBySemicolumn,
                        timeOutInMillis});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void checkPortsAsync(string host, string portsToCheckDelimitedBySemicolumn, int timeOutInMillis) {
            this.checkPortsAsync(host, portsToCheckDelimitedBySemicolumn, timeOutInMillis, null);
        }
        
        /// <remarks/>
        public void checkPortsAsync(string host, string portsToCheckDelimitedBySemicolumn, int timeOutInMillis, object userState) {
            if ((this.checkPortsOperationCompleted == null)) {
                this.checkPortsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckPortsOperationCompleted);
            }
            this.InvokeAsync("checkPorts", new object[] {
                        host,
                        portsToCheckDelimitedBySemicolumn,
                        timeOutInMillis}, this.checkPortsOperationCompleted, userState);
        }
        
        private void OncheckPortsOperationCompleted(object arg) {
            if ((this.checkPortsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkPortsCompleted(this, new checkPortsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.mule.mproxy.cmp.com/")]
    public partial class mproxyOperationStatusError {
        
        private string detailedInfoField;
        
        private mproxyOperationResult operationResultField;
        
        private bool operationResultFieldSpecified;
        
        private errorLog[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string detailedInfo {
            get {
                return this.detailedInfoField;
            }
            set {
                this.detailedInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mproxyOperationResult operationResult {
            get {
                return this.operationResultField;
            }
            set {
                this.operationResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationResultSpecified {
            get {
                return this.operationResultFieldSpecified;
            }
            set {
                this.operationResultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public errorLog[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.mule.mproxy.cmp.com/")]
    public enum mproxyOperationResult {
        
        /// <remarks/>
        MPROXY_RESULT_OK,
        
        /// <remarks/>
        MPROXY_RESULT_FAILED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.mule.mproxy.cmp.com/")]
    public partial class errorLog {
        
        private System.DateTime creationDateField;
        
        private bool creationDateFieldSpecified;
        
        private string errorMessageField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private long mproxyErrorIdField;
        
        private string muleComponentField;
        
        private string stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime creationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationDateSpecified {
            get {
                return this.creationDateFieldSpecified;
            }
            set {
                this.creationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mproxyErrorId {
            get {
                return this.mproxyErrorIdField;
            }
            set {
                this.mproxyErrorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string muleComponent {
            get {
                return this.muleComponentField;
            }
            set {
                this.muleComponentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.mule.mproxy.cmp.com/")]
    public partial class mproxyOperationStatus {
        
        private string detailedInfoField;
        
        private string operationOutputValueField;
        
        private mproxyOperationResult operationResultField;
        
        private bool operationResultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string detailedInfo {
            get {
                return this.detailedInfoField;
            }
            set {
                this.detailedInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operationOutputValue {
            get {
                return this.operationOutputValueField;
            }
            set {
                this.operationOutputValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mproxyOperationResult operationResult {
            get {
                return this.operationResultField;
            }
            set {
                this.operationResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationResultSpecified {
            get {
                return this.operationResultFieldSpecified;
            }
            set {
                this.operationResultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getErrorByIdCompletedEventHandler(object sender, getErrorByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getErrorByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getErrorByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusError Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusError)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getMbeanAttributeCompletedEventHandler(object sender, getMbeanAttributeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMbeanAttributeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMbeanAttributeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void exportErrorsToFileCompletedEventHandler(object sender, exportErrorsToFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class exportErrorsToFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal exportErrorsToFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void clearErrorsCompletedEventHandler(object sender, clearErrorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class clearErrorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal clearErrorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void checkPortsListenCompletedEventHandler(object sender, checkPortsListenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkPortsListenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkPortsListenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void findLastErrorsCompletedEventHandler(object sender, findLastErrorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findLastErrorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findLastErrorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusError Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusError)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void findAllErrorsCompletedEventHandler(object sender, findAllErrorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findAllErrorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findAllErrorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusError Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusError)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void removeErrorByIdCompletedEventHandler(object sender, removeErrorByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeErrorByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeErrorByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void checkPortsCompletedEventHandler(object sender, checkPortsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkPortsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkPortsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591