//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace MMCoreConnector.WRQueueManagement {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QueueManagerServiceSoapBinding", Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractCollection))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mproxyAttachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dictionary))]
    public partial class QueueManagerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback flushMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendEHealthMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback reprocessMessageByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback flushAllMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteAllMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessageIdsByTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendAllMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendSimpleMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessageIdsByKindAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessageByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendAsXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback getIMessageByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessageIdsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMediMailDynamicVariablesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QueueManagerService() {
            this.Url = global::MMCoreConnector.Properties.Settings.Default.MMCoreConnector_WRQueueManagement_QueueManagerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event flushMessageCompletedEventHandler flushMessageCompleted;
        
        /// <remarks/>
        public event sendEHealthMessageCompletedEventHandler sendEHealthMessageCompleted;
        
        /// <remarks/>
        public event reprocessMessageByIdCompletedEventHandler reprocessMessageByIdCompleted;
        
        /// <remarks/>
        public event flushAllMessagesCompletedEventHandler flushAllMessagesCompleted;
        
        /// <remarks/>
        public event deleteAllMessagesCompletedEventHandler deleteAllMessagesCompleted;
        
        /// <remarks/>
        public event getMessageIdsByTypeCompletedEventHandler getMessageIdsByTypeCompleted;
        
        /// <remarks/>
        public event sendAllMessagesCompletedEventHandler sendAllMessagesCompleted;
        
        /// <remarks/>
        public event deleteMessageCompletedEventHandler deleteMessageCompleted;
        
        /// <remarks/>
        public event sendSimpleMessageCompletedEventHandler sendSimpleMessageCompleted;
        
        /// <remarks/>
        public event getMessageIdsByKindAccountCompletedEventHandler getMessageIdsByKindAccountCompleted;
        
        /// <remarks/>
        public event getMessageByIdCompletedEventHandler getMessageByIdCompleted;
        
        /// <remarks/>
        public event sendAsXmlCompletedEventHandler sendAsXmlCompleted;
        
        /// <remarks/>
        public event getIMessageByIdCompletedEventHandler getIMessageByIdCompleted;
        
        /// <remarks/>
        public event getMessageIdsCompletedEventHandler getMessageIdsCompleted;
        
        /// <remarks/>
        public event getMediMailDynamicVariablesCompletedEventHandler getMediMailDynamicVariablesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus flushMessage(int mailBoxMessageId) {
            object[] results = this.Invoke("flushMessage", new object[] {
                        mailBoxMessageId});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void flushMessageAsync(int mailBoxMessageId) {
            this.flushMessageAsync(mailBoxMessageId, null);
        }
        
        /// <remarks/>
        public void flushMessageAsync(int mailBoxMessageId, object userState) {
            if ((this.flushMessageOperationCompleted == null)) {
                this.flushMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnflushMessageOperationCompleted);
            }
            this.InvokeAsync("flushMessage", new object[] {
                        mailBoxMessageId}, this.flushMessageOperationCompleted, userState);
        }
        
        private void OnflushMessageOperationCompleted(object arg) {
            if ((this.flushMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.flushMessageCompleted(this, new flushMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus sendEHealthMessage(string mailBoxAccountId, string ehealthType, string ehealthValue, string ehealthAppID, string fileLocation, string subject, string textMessage) {
            object[] results = this.Invoke("sendEHealthMessage", new object[] {
                        mailBoxAccountId,
                        ehealthType,
                        ehealthValue,
                        ehealthAppID,
                        fileLocation,
                        subject,
                        textMessage});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void sendEHealthMessageAsync(string mailBoxAccountId, string ehealthType, string ehealthValue, string ehealthAppID, string fileLocation, string subject, string textMessage) {
            this.sendEHealthMessageAsync(mailBoxAccountId, ehealthType, ehealthValue, ehealthAppID, fileLocation, subject, textMessage, null);
        }
        
        /// <remarks/>
        public void sendEHealthMessageAsync(string mailBoxAccountId, string ehealthType, string ehealthValue, string ehealthAppID, string fileLocation, string subject, string textMessage, object userState) {
            if ((this.sendEHealthMessageOperationCompleted == null)) {
                this.sendEHealthMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendEHealthMessageOperationCompleted);
            }
            this.InvokeAsync("sendEHealthMessage", new object[] {
                        mailBoxAccountId,
                        ehealthType,
                        ehealthValue,
                        ehealthAppID,
                        fileLocation,
                        subject,
                        textMessage}, this.sendEHealthMessageOperationCompleted, userState);
        }
        
        private void OnsendEHealthMessageOperationCompleted(object arg) {
            if ((this.sendEHealthMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendEHealthMessageCompleted(this, new sendEHealthMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus reprocessMessageById(int messageId) {
            object[] results = this.Invoke("reprocessMessageById", new object[] {
                        messageId});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void reprocessMessageByIdAsync(int messageId) {
            this.reprocessMessageByIdAsync(messageId, null);
        }
        
        /// <remarks/>
        public void reprocessMessageByIdAsync(int messageId, object userState) {
            if ((this.reprocessMessageByIdOperationCompleted == null)) {
                this.reprocessMessageByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreprocessMessageByIdOperationCompleted);
            }
            this.InvokeAsync("reprocessMessageById", new object[] {
                        messageId}, this.reprocessMessageByIdOperationCompleted, userState);
        }
        
        private void OnreprocessMessageByIdOperationCompleted(object arg) {
            if ((this.reprocessMessageByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reprocessMessageByIdCompleted(this, new reprocessMessageByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus flushAllMessages(string mailBoxAccountId) {
            object[] results = this.Invoke("flushAllMessages", new object[] {
                        mailBoxAccountId});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void flushAllMessagesAsync(string mailBoxAccountId) {
            this.flushAllMessagesAsync(mailBoxAccountId, null);
        }
        
        /// <remarks/>
        public void flushAllMessagesAsync(string mailBoxAccountId, object userState) {
            if ((this.flushAllMessagesOperationCompleted == null)) {
                this.flushAllMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnflushAllMessagesOperationCompleted);
            }
            this.InvokeAsync("flushAllMessages", new object[] {
                        mailBoxAccountId}, this.flushAllMessagesOperationCompleted, userState);
        }
        
        private void OnflushAllMessagesOperationCompleted(object arg) {
            if ((this.flushAllMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.flushAllMessagesCompleted(this, new flushAllMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus deleteAllMessages(string mailBoxAccountId, mailBoxType mailBoxType) {
            object[] results = this.Invoke("deleteAllMessages", new object[] {
                        mailBoxAccountId,
                        mailBoxType});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAllMessagesAsync(string mailBoxAccountId, mailBoxType mailBoxType) {
            this.deleteAllMessagesAsync(mailBoxAccountId, mailBoxType, null);
        }
        
        /// <remarks/>
        public void deleteAllMessagesAsync(string mailBoxAccountId, mailBoxType mailBoxType, object userState) {
            if ((this.deleteAllMessagesOperationCompleted == null)) {
                this.deleteAllMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteAllMessagesOperationCompleted);
            }
            this.InvokeAsync("deleteAllMessages", new object[] {
                        mailBoxAccountId,
                        mailBoxType}, this.deleteAllMessagesOperationCompleted, userState);
        }
        
        private void OndeleteAllMessagesOperationCompleted(object arg) {
            if ((this.deleteAllMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteAllMessagesCompleted(this, new deleteAllMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusStrings getMessageIdsByType(string mailBoxAccountId, string mailBoxType) {
            object[] results = this.Invoke("getMessageIdsByType", new object[] {
                        mailBoxAccountId,
                        mailBoxType});
            return ((mproxyOperationStatusStrings)(results[0]));
        }
        
        /// <remarks/>
        public void getMessageIdsByTypeAsync(string mailBoxAccountId, string mailBoxType) {
            this.getMessageIdsByTypeAsync(mailBoxAccountId, mailBoxType, null);
        }
        
        /// <remarks/>
        public void getMessageIdsByTypeAsync(string mailBoxAccountId, string mailBoxType, object userState) {
            if ((this.getMessageIdsByTypeOperationCompleted == null)) {
                this.getMessageIdsByTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessageIdsByTypeOperationCompleted);
            }
            this.InvokeAsync("getMessageIdsByType", new object[] {
                        mailBoxAccountId,
                        mailBoxType}, this.getMessageIdsByTypeOperationCompleted, userState);
        }
        
        private void OngetMessageIdsByTypeOperationCompleted(object arg) {
            if ((this.getMessageIdsByTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessageIdsByTypeCompleted(this, new getMessageIdsByTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus sendAllMessages(string mailBoxAccountId) {
            object[] results = this.Invoke("sendAllMessages", new object[] {
                        mailBoxAccountId});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void sendAllMessagesAsync(string mailBoxAccountId) {
            this.sendAllMessagesAsync(mailBoxAccountId, null);
        }
        
        /// <remarks/>
        public void sendAllMessagesAsync(string mailBoxAccountId, object userState) {
            if ((this.sendAllMessagesOperationCompleted == null)) {
                this.sendAllMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendAllMessagesOperationCompleted);
            }
            this.InvokeAsync("sendAllMessages", new object[] {
                        mailBoxAccountId}, this.sendAllMessagesOperationCompleted, userState);
        }
        
        private void OnsendAllMessagesOperationCompleted(object arg) {
            if ((this.sendAllMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendAllMessagesCompleted(this, new sendAllMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus deleteMessage(int mailBoxMessageId) {
            object[] results = this.Invoke("deleteMessage", new object[] {
                        mailBoxMessageId});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void deleteMessageAsync(int mailBoxMessageId) {
            this.deleteMessageAsync(mailBoxMessageId, null);
        }
        
        /// <remarks/>
        public void deleteMessageAsync(int mailBoxMessageId, object userState) {
            if ((this.deleteMessageOperationCompleted == null)) {
                this.deleteMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteMessageOperationCompleted);
            }
            this.InvokeAsync("deleteMessage", new object[] {
                        mailBoxMessageId}, this.deleteMessageOperationCompleted, userState);
        }
        
        private void OndeleteMessageOperationCompleted(object arg) {
            if ((this.deleteMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteMessageCompleted(this, new deleteMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus sendSimpleMessage(string mailBoxAccountId, string destinationLdapUid, string fileLocation, string subject, string textMessage) {
            object[] results = this.Invoke("sendSimpleMessage", new object[] {
                        mailBoxAccountId,
                        destinationLdapUid,
                        fileLocation,
                        subject,
                        textMessage});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void sendSimpleMessageAsync(string mailBoxAccountId, string destinationLdapUid, string fileLocation, string subject, string textMessage) {
            this.sendSimpleMessageAsync(mailBoxAccountId, destinationLdapUid, fileLocation, subject, textMessage, null);
        }
        
        /// <remarks/>
        public void sendSimpleMessageAsync(string mailBoxAccountId, string destinationLdapUid, string fileLocation, string subject, string textMessage, object userState) {
            if ((this.sendSimpleMessageOperationCompleted == null)) {
                this.sendSimpleMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendSimpleMessageOperationCompleted);
            }
            this.InvokeAsync("sendSimpleMessage", new object[] {
                        mailBoxAccountId,
                        destinationLdapUid,
                        fileLocation,
                        subject,
                        textMessage}, this.sendSimpleMessageOperationCompleted, userState);
        }
        
        private void OnsendSimpleMessageOperationCompleted(object arg) {
            if ((this.sendSimpleMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendSimpleMessageCompleted(this, new sendSimpleMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusStrings getMessageIdsByKindAccount(string accountId, mailBoxType mailBoxTypeId) {
            object[] results = this.Invoke("getMessageIdsByKindAccount", new object[] {
                        accountId,
                        mailBoxTypeId});
            return ((mproxyOperationStatusStrings)(results[0]));
        }
        
        /// <remarks/>
        public void getMessageIdsByKindAccountAsync(string accountId, mailBoxType mailBoxTypeId) {
            this.getMessageIdsByKindAccountAsync(accountId, mailBoxTypeId, null);
        }
        
        /// <remarks/>
        public void getMessageIdsByKindAccountAsync(string accountId, mailBoxType mailBoxTypeId, object userState) {
            if ((this.getMessageIdsByKindAccountOperationCompleted == null)) {
                this.getMessageIdsByKindAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessageIdsByKindAccountOperationCompleted);
            }
            this.InvokeAsync("getMessageIdsByKindAccount", new object[] {
                        accountId,
                        mailBoxTypeId}, this.getMessageIdsByKindAccountOperationCompleted, userState);
        }
        
        private void OngetMessageIdsByKindAccountOperationCompleted(object arg) {
            if ((this.getMessageIdsByKindAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessageIdsByKindAccountCompleted(this, new getMessageIdsByKindAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusMessage getMessageById(int messageId) {
            object[] results = this.Invoke("getMessageById", new object[] {
                        messageId});
            return ((mproxyOperationStatusMessage)(results[0]));
        }
        
        /// <remarks/>
        public void getMessageByIdAsync(int messageId) {
            this.getMessageByIdAsync(messageId, null);
        }
        
        /// <remarks/>
        public void getMessageByIdAsync(int messageId, object userState) {
            if ((this.getMessageByIdOperationCompleted == null)) {
                this.getMessageByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessageByIdOperationCompleted);
            }
            this.InvokeAsync("getMessageById", new object[] {
                        messageId}, this.getMessageByIdOperationCompleted, userState);
        }
        
        private void OngetMessageByIdOperationCompleted(object arg) {
            if ((this.getMessageByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessageByIdCompleted(this, new getMessageByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatus sendAsXml(string mailBoxAccountId, string xmlMessageB64) {
            object[] results = this.Invoke("sendAsXml", new object[] {
                        mailBoxAccountId,
                        xmlMessageB64});
            return ((mproxyOperationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void sendAsXmlAsync(string mailBoxAccountId, string xmlMessageB64) {
            this.sendAsXmlAsync(mailBoxAccountId, xmlMessageB64, null);
        }
        
        /// <remarks/>
        public void sendAsXmlAsync(string mailBoxAccountId, string xmlMessageB64, object userState) {
            if ((this.sendAsXmlOperationCompleted == null)) {
                this.sendAsXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendAsXmlOperationCompleted);
            }
            this.InvokeAsync("sendAsXml", new object[] {
                        mailBoxAccountId,
                        xmlMessageB64}, this.sendAsXmlOperationCompleted, userState);
        }
        
        private void OnsendAsXmlOperationCompleted(object arg) {
            if ((this.sendAsXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendAsXmlCompleted(this, new sendAsXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusIMessage getIMessageById(int messageId) {
            object[] results = this.Invoke("getIMessageById", new object[] {
                        messageId});
            return ((mproxyOperationStatusIMessage)(results[0]));
        }
        
        /// <remarks/>
        public void getIMessageByIdAsync(int messageId) {
            this.getIMessageByIdAsync(messageId, null);
        }
        
        /// <remarks/>
        public void getIMessageByIdAsync(int messageId, object userState) {
            if ((this.getIMessageByIdOperationCompleted == null)) {
                this.getIMessageByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetIMessageByIdOperationCompleted);
            }
            this.InvokeAsync("getIMessageById", new object[] {
                        messageId}, this.getIMessageByIdOperationCompleted, userState);
        }
        
        private void OngetIMessageByIdOperationCompleted(object arg) {
            if ((this.getIMessageByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getIMessageByIdCompleted(this, new getIMessageByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusStrings getMessageIds(string mailBoxAccountId) {
            object[] results = this.Invoke("getMessageIds", new object[] {
                        mailBoxAccountId});
            return ((mproxyOperationStatusStrings)(results[0]));
        }
        
        /// <remarks/>
        public void getMessageIdsAsync(string mailBoxAccountId) {
            this.getMessageIdsAsync(mailBoxAccountId, null);
        }
        
        /// <remarks/>
        public void getMessageIdsAsync(string mailBoxAccountId, object userState) {
            if ((this.getMessageIdsOperationCompleted == null)) {
                this.getMessageIdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessageIdsOperationCompleted);
            }
            this.InvokeAsync("getMessageIds", new object[] {
                        mailBoxAccountId}, this.getMessageIdsOperationCompleted, userState);
        }
        
        private void OngetMessageIdsOperationCompleted(object arg) {
            if ((this.getMessageIdsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessageIdsCompleted(this, new getMessageIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://operations.management.medimail.mproxy.cmp.com/", ResponseNamespace="http://operations.management.medimail.mproxy.cmp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mproxyOperationStatusStrings getMediMailDynamicVariables() {
            object[] results = this.Invoke("getMediMailDynamicVariables", new object[0]);
            return ((mproxyOperationStatusStrings)(results[0]));
        }
        
        /// <remarks/>
        public void getMediMailDynamicVariablesAsync() {
            this.getMediMailDynamicVariablesAsync(null);
        }
        
        /// <remarks/>
        public void getMediMailDynamicVariablesAsync(object userState) {
            if ((this.getMediMailDynamicVariablesOperationCompleted == null)) {
                this.getMediMailDynamicVariablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMediMailDynamicVariablesOperationCompleted);
            }
            this.InvokeAsync("getMediMailDynamicVariables", new object[0], this.getMediMailDynamicVariablesOperationCompleted, userState);
        }
        
        private void OngetMediMailDynamicVariablesOperationCompleted(object arg) {
            if ((this.getMediMailDynamicVariablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMediMailDynamicVariablesCompleted(this, new getMediMailDynamicVariablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public partial class mproxyOperationStatus {
        
        private string detailedInfoField;
        
        private string operationOutputValueField;
        
        private mproxyOperationResult operationResultField;
        
        private bool operationResultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string detailedInfo {
            get {
                return this.detailedInfoField;
            }
            set {
                this.detailedInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operationOutputValue {
            get {
                return this.operationOutputValueField;
            }
            set {
                this.operationOutputValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mproxyOperationResult operationResult {
            get {
                return this.operationResultField;
            }
            set {
                this.operationResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationResultSpecified {
            get {
                return this.operationResultFieldSpecified;
            }
            set {
                this.operationResultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public enum mproxyOperationResult {
        
        /// <remarks/>
        MPROXY_RESULT_OK,
        
        /// <remarks/>
        MPROXY_RESULT_FAILED,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hashSet))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public abstract partial class abstractCollection {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hashSet))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public abstract partial class abstractSet : abstractCollection {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public partial class hashSet : abstractSet {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public partial class mproxyAttachment {
        
        private string attachmentIdField;
        
        private byte[] contentField;
        
        private string infoField;
        
        private string nameField;
        
        private mproxyMessageStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attachmentId {
            get {
                return this.attachmentIdField;
            }
            set {
                this.attachmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mproxyMessageStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public enum mproxyMessageStatus {
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        MMS_MESSAGE_ENQUIRED_FOR_ENCODING,
        
        /// <remarks/>
        MMS_MESSAGE_ENQUIRED_FOR_DECODING,
        
        /// <remarks/>
        MMS_MESSAGE_FAILED_TO_ENCODE,
        
        /// <remarks/>
        MMS_MESSAGE_FAILED_TO_DECODE,
        
        /// <remarks/>
        MMS_MESSAGE_SUCCESSFULLY_ENCODED,
        
        /// <remarks/>
        MMS_MESSAGE_SUCCESSFULLY_DECODED,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hashtable))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(properties))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public abstract partial class dictionary {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(properties))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public partial class hashtable : dictionary {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public partial class properties : hashtable {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public partial class mproxyIntegrationMessage {
        
        private mproxyIntegrationMessageEntry[] metadataField;
        
        private string mproxyXMLMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public mproxyIntegrationMessageEntry[] metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mproxyXMLMessage {
            get {
                return this.mproxyXMLMessageField;
            }
            set {
                this.mproxyXMLMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public partial class mproxyIntegrationMessageEntry {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public partial class mproxyOperationStatusIMessage {
        
        private string detailedInfoField;
        
        private mproxyOperationResult operationResultField;
        
        private bool operationResultFieldSpecified;
        
        private mproxyIntegrationMessage[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string detailedInfo {
            get {
                return this.detailedInfoField;
            }
            set {
                this.detailedInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mproxyOperationResult operationResult {
            get {
                return this.operationResultField;
            }
            set {
                this.operationResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationResultSpecified {
            get {
                return this.operationResultFieldSpecified;
            }
            set {
                this.operationResultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public mproxyIntegrationMessage[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public partial class mailBoxMessageData {
        
        private byte[] blobField;
        
        private byte[] checkSumField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private byte[] mproxyMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] blob {
            get {
                return this.blobField;
            }
            set {
                this.blobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] checkSum {
            get {
                return this.checkSumField;
            }
            set {
                this.checkSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] mproxyMessage {
            get {
                return this.mproxyMessageField;
            }
            set {
                this.mproxyMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public partial class mailBoxMessage {
        
        private string accountField;
        
        private int attachmentNumberField;
        
        private bool attachmentNumberFieldSpecified;
        
        private int attachmentsTotalField;
        
        private bool attachmentsTotalFieldSpecified;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string guidField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private mailBoxMessageData infoField;
        
        private mailBoxType locationField;
        
        private bool locationFieldSpecified;
        
        private mailBoxMessageKind messageKindField;
        
        private bool messageKindFieldSpecified;
        
        private int partNumberField;
        
        private bool partNumberFieldSpecified;
        
        private int partsTotalField;
        
        private bool partsTotalFieldSpecified;
        
        private string receiverField;
        
        private string resourceNameField;
        
        private string senderField;
        
        private mailBoxMessageStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int attachmentNumber {
            get {
                return this.attachmentNumberField;
            }
            set {
                this.attachmentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentNumberSpecified {
            get {
                return this.attachmentNumberFieldSpecified;
            }
            set {
                this.attachmentNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int attachmentsTotal {
            get {
                return this.attachmentsTotalField;
            }
            set {
                this.attachmentsTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentsTotalSpecified {
            get {
                return this.attachmentsTotalFieldSpecified;
            }
            set {
                this.attachmentsTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mailBoxMessageData info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mailBoxType location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool locationSpecified {
            get {
                return this.locationFieldSpecified;
            }
            set {
                this.locationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mailBoxMessageKind messageKind {
            get {
                return this.messageKindField;
            }
            set {
                this.messageKindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messageKindSpecified {
            get {
                return this.messageKindFieldSpecified;
            }
            set {
                this.messageKindFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int partNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool partNumberSpecified {
            get {
                return this.partNumberFieldSpecified;
            }
            set {
                this.partNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int partsTotal {
            get {
                return this.partsTotalField;
            }
            set {
                this.partsTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool partsTotalSpecified {
            get {
                return this.partsTotalFieldSpecified;
            }
            set {
                this.partsTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resourceName {
            get {
                return this.resourceNameField;
            }
            set {
                this.resourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mailBoxMessageStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public enum mailBoxType {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        INBOX,
        
        /// <remarks/>
        OUTBOX,
        
        /// <remarks/>
        SENTBOX,
        
        /// <remarks/>
        TRASH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public enum mailBoxMessageKind {
        
        /// <remarks/>
        NORMAL,
        
        /// <remarks/>
        PARTITIONED,
        
        /// <remarks/>
        ACKNOWLEDGE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public enum mailBoxMessageStatus {
        
        /// <remarks/>
        CERTIFICATION_APPROVED,
        
        /// <remarks/>
        FLUSHED,
        
        /// <remarks/>
        FLUSHING,
        
        /// <remarks/>
        GENERAL_ERROR,
        
        /// <remarks/>
        IN_PROCESS,
        
        /// <remarks/>
        MERGED,
        
        /// <remarks/>
        NOT_MERGED,
        
        /// <remarks/>
        NOT_READ,
        
        /// <remarks/>
        READ,
        
        /// <remarks/>
        RECEIVE_ERROR,
        
        /// <remarks/>
        RECEIVED,
        
        /// <remarks/>
        SEND_ERROR,
        
        /// <remarks/>
        SENDING,
        
        /// <remarks/>
        SENT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public partial class mproxyOperationStatusMessage {
        
        private string detailedInfoField;
        
        private mproxyOperationResult operationResultField;
        
        private bool operationResultFieldSpecified;
        
        private mailBoxMessage[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string detailedInfo {
            get {
                return this.detailedInfoField;
            }
            set {
                this.detailedInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mproxyOperationResult operationResult {
            get {
                return this.operationResultField;
            }
            set {
                this.operationResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationResultSpecified {
            get {
                return this.operationResultFieldSpecified;
            }
            set {
                this.operationResultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public mailBoxMessage[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.management.medimail.mproxy.cmp.com/")]
    public partial class mproxyOperationStatusStrings {
        
        private string detailedInfoField;
        
        private mproxyOperationResult operationResultField;
        
        private bool operationResultFieldSpecified;
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string detailedInfo {
            get {
                return this.detailedInfoField;
            }
            set {
                this.detailedInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mproxyOperationResult operationResult {
            get {
                return this.operationResultField;
            }
            set {
                this.operationResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationResultSpecified {
            get {
                return this.operationResultFieldSpecified;
            }
            set {
                this.operationResultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void flushMessageCompletedEventHandler(object sender, flushMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class flushMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal flushMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void sendEHealthMessageCompletedEventHandler(object sender, sendEHealthMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendEHealthMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendEHealthMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void reprocessMessageByIdCompletedEventHandler(object sender, reprocessMessageByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reprocessMessageByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reprocessMessageByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void flushAllMessagesCompletedEventHandler(object sender, flushAllMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class flushAllMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal flushAllMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void deleteAllMessagesCompletedEventHandler(object sender, deleteAllMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteAllMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteAllMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getMessageIdsByTypeCompletedEventHandler(object sender, getMessageIdsByTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessageIdsByTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessageIdsByTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusStrings Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusStrings)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void sendAllMessagesCompletedEventHandler(object sender, sendAllMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendAllMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendAllMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void deleteMessageCompletedEventHandler(object sender, deleteMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void sendSimpleMessageCompletedEventHandler(object sender, sendSimpleMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendSimpleMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendSimpleMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getMessageIdsByKindAccountCompletedEventHandler(object sender, getMessageIdsByKindAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessageIdsByKindAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessageIdsByKindAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusStrings Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusStrings)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getMessageByIdCompletedEventHandler(object sender, getMessageByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessageByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessageByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void sendAsXmlCompletedEventHandler(object sender, sendAsXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendAsXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendAsXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getIMessageByIdCompletedEventHandler(object sender, getIMessageByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getIMessageByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getIMessageByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusIMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusIMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getMessageIdsCompletedEventHandler(object sender, getMessageIdsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessageIdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessageIdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusStrings Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusStrings)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getMediMailDynamicVariablesCompletedEventHandler(object sender, getMediMailDynamicVariablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMediMailDynamicVariablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMediMailDynamicVariablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mproxyOperationStatusStrings Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mproxyOperationStatusStrings)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591